Blog/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'about', to: 'users#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/search', to: 'posts#search'
  get '/search2', to: 'posts#searchtitle'
  get '/success', to: 'users#success'
  root 'users#new'
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 14000 }, presence: true
end

Blog/app/models/user.rb
class User < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	has_many :posts, dependent: :destroy
	validates :name, length: { maximum: 50 }, presence: true # 把 FILL_IN 换成正确的代码
  	validates :email, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, presence: true, uniqueness: {case_sensitive: false} # 把 FILL_IN 换成正确的代码
  	has_secure_password
  	validates :password, presence: true, length: { minimum: 8 }
end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def search
    @posts = Post.all
    @result = params[:q];
  end

  def searchtitle
    @posts = Post.all
    @result = params[:q];
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.author = current_user.name
    respond_to do |format|
      if @post.save
        format.html { redirect_to '/success', notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to '/success', notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to '/success', notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

Blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
	user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])
	# 登入用户，然后重定向到用户的资料页面
		log_in user
		redirect_to root_url
	else
	# 创建一个错误消息
	flash[:danger] = 'Invalid email/password combination' #
	render 'new'
	end
end

  def destroy
  	log_out
  	redirect_to root_url
  end

  def new
  end
end

Blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy
  before_action :correct_user, only: [:edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user #user log in automatically after registered
        format.html { redirect_to '/success', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to '/success', notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # 确保是正确的用户
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/posts_helper.rb
module PostsHelper
end

Blog/app/helpers/sessions_helper.rb
module SessionsHelper
	#log in user
	def log_in(user)
		session[:user_id] = user.id
	end

	#return the user if it exist
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	#check log in or not
	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

Blog/app/helpers/users_helper.rb
module UsersHelper
	# 返回指定用户的 Gravatar
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

Blog/app/views/layouts/_footer.html.erb
<footer class="footer">
<p>
	LyuBlog Version:4.0 (2017/1/12) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Made by Nuochen Lyu 吕诺晨&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; lnc0519@gmail.com
</p>
</footer>

Blog/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="opacity: 0.7; height: 6%;">
<div class="nav-bar">
	<%= link_to "", root_path, id: "logo" %>
	<nav>
	<ul class="nav navbar-nav navbar-right" style="margin-top:4.5px; margin-right: 10px;">
		<li><a href="http://www.lyulyulyu.com">LyuLyuLyu.com</a></li>
		<li><%= link_to "About", 'about' %></li>
		<li><%= link_to "Explore", posts_path %></li>
		<li><%= link_to "Users", users_path %></li>
		<% if logged_in? %>
			<li><%= link_to "Your Profile", current_user %></li>
			<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			Account <b class="caret"></b>
			</a>
			<ul class="dropdown-menu">
				<li><%= link_to "Settings", edit_user_path(current_user) %></li>
				<li>
				<%= link_to "Log out", logout_path, method: "delete" %>
				</li>
			</ul>
		</li>
	<% else %>
		<li><%= link_to "Log in", login_path%></li>
	<% end %>
	</ul>
	</nav>
</div>
</header>

Blog/app/views/layouts/application.html.erb
<html>
<head>
	<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	<%= csrf_meta_tags %>
	<link href='https://fonts.googleapis.com/css?family=Lato:100italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag 'application', media: 'all',
	'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta charset="UTF-8">
</head>
<body>
	  <%= render 'layouts/header' %>
		  <%= yield %>
	  <%= render 'layouts/footer' %>
</body>
</html>

Blog/app/views/posts/_form.html.erb
<div class="newblog">
  <%= form_for(post) do |f| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <div>
      <%= f.label :title %>
      </div>
      <div>
      <%= f.text_area :title %>
      </div>
      <div>
      <%= f.label :content %>
      </div>
      <div>
      <%= f.text_area :content %>
      </div>
      <!--
      <div>
      <%= f.label :user_id %>
      </div>
      <div>
      <p>your id is <%= current_user.id %></p>
     <div>
      <p>your id is <%= current_user.name %></p>
      </div>
      title<%= post.title %>
      <% post.user_id = current_user.id %>
       post id is<%= post.user_id %>
      <% if post.user_id != nil %>
      <%= post.user_id %>
      <% end %>
      </div>
      -->
    <div class="btn">
      <%= f.submit %>
    </div>
  <% end %>
</div>

Blog/app/views/posts/_post.html.erb
<p id="notice"><%= notice %></p>
  <div class='listbody'>
    <div style="background-color: white; width: 50%; height:2px; display: inline-block;">
    </div>
      <div style="font-size: 2vw; margin-top: 2.7%; text-align: center;">
        <p style="font-size: 3.5vw; font-weight: 900;"><%= post.title %></p>
      </div>
      <div style="margin-bottom: 5%; margin-left: 2%; margin-right: 2%; ">
        <div style="text-align: left; margin-left: 3%; margin-right: 3%; font-size: 24px; margin-bottom: 6%; margin-top: 6%;">
            <p><%= simple_format post.content %></p>
        </div>
        <p style="font-size: 1.8vw;">Post by: <%= post.author %></p>
        <p><%= post.updated_at %></p>
        <p style="font-size: 1.5vw;">
          <%= link_to 'Showpost', post %> 
          <% if current_user != nil && current_user.id == @user.id%>     
          <%= link_to 'Editpost', edit_post_path(post) %>        
          <%= link_to 'Destroypost', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %> 
        </p>
        <div style="background-color: white; width: 50%; height:2px; display: inline-block;">
        </div>
      </div>
  </div>
<br>

Blog/app/views/posts/edit.html.erb
<div class="intro" style="margin-top: 8%;">
	<p>Edit your post</p>
	<p><%= link_to 'Back', current_user %></p>
</div>
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> | 
<%= link_to 'Back to post', posts_path %>

Blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="intro" style="margin-top: 8%; margin-bottom: 7%; font-size: 1.7vw;">
<p>Posts</p>
<div class="searchtag">
<%= form_tag({action: "search"}, method: "get") do %>
  <%= text_field_tag(:q, nil, placeholder: 'Enter author name here') %>
  <br>
  <%= submit_tag("Search by author") %>
<% end %>
<%= form_tag({action: "searchtitle"}, method: "get") do %>
  <%= text_field_tag(:q, nil, placeholder: 'Enter blog title here') %>
  <br>
  <%= submit_tag("Search by title") %>
<% end %>
<br>
<br>
</div>
<% if current_user != nil%>
<p ><%= link_to 'New Post', new_post_path %></p>
<% else %>
<p style="font-size: 2vw; color: yellow; font-weight: 900;"> View only, you have not logged in </p>
<% end %>
<p style="font-size: 1.4vw;">恰同学少年，风华正茂。</p>
</div>
    <% @posts.each do |post| %>
    <div class="postlist">
      <div style="font-size: 6vw; text-align: center;color:black; background-color: white; margin-bottom: -1.5%;">
        <p><%= simple_format post.title %></p>
      </div>
      <div style="color:white; background-color: black; padding-top: 1%;text-align: center;">
        <div style="text-align: left; margin-left: 3%; margin-right: 3%; font-size: 24px; margin-bottom: 6%; margin-top: 6%;">
            <p><%= simple_format post.content %></p>
        </div>
        <p style="font-size: 1.8vw;">Author: <%= post.author %></p>
        <p><%= post.created_at %>&nbsp;<%= post.updated_at %></p>
        <p style="background-color: white; color:black;margin-bottom: 20%;"><%= link_to 'Showpost', post %></p>
      </div>
    </div>
    <% end %>

Blog/app/views/posts/new.html.erb
<div class="intro" style="margin-top: 8%;">
	<p>New Post</p>
	<p><%= link_to 'Back', posts_path %></p>
</div>

<%= render 'form', post: @post %>

Blog/app/views/posts/search.html.erb
<p id="notice"><%= notice %></p>
<div class="intro" style="margin-top: 8%; margin-bottom: 7%; font-size: 1.7vw;">
<p>Searching Center</p>
<p ><%= link_to 'Back', 'posts#index' %></p>
<p style="font-size: 2.4vw; font-weight: 900; color: yellow;">Searching for author: <%= @result %></p>
</div>
	<% counter = 0 %>
	<% if @result == "" or @result == " " or @result == "  " or @result == "   " %>
		<p style="color: yellow; text-align: center; margin-top: 8%; margin-bottom: 7%; font-size: 3.7vw;">Your search cannot be blank!</p>
	<% else %>
	    <% @posts.each do |post| %>
	    	<% if post.author.include? @result %>
	    		<% counter = counter+1 %>
			    <div class="postlist">
			      <div style="font-size: 6vw; text-align: center;color:black; background-color: white; margin-bottom: -1.5%;">
			        <p><%= post.title %></p>
			      </div>
			      <div style="color:white; background-color: black; padding-top: 1%;">
			        <div style="text-align: left; margin-left: 3%; margin-right: 3%; font-size: 24px; margin-bottom: 6%; margin-top: 6%;">
            			<p><%= simple_format post.content %></p>
      				</div>
			        <p style="font-size: 1.8vw;">Author: <%= post.author %></p>
			        <p><%= post.created_at %>&nbsp;<%= post.updated_at %></p>
			        <p style="background-color: white; color:black;margin-bottom: 20%;"><%= link_to 'Showpost', post %></p>
			      </div>
			    </div>
			<% end %>
	    <% end %>
	    <% if counter == 0 %>
			<p style="color: yellow; text-align: center; margin-top: 8%; margin-bottom: 7%; font-size: 3.7vw;">Sorry, the author is not found :(</p>
		<% end %>
	<% end %>

Blog/app/views/posts/searchtitle.html.erb
<p id="notice"><%= notice %></p>
<div class="intro" style="margin-top: 8%; margin-bottom: 7%; font-size: 1.7vw;">
<p>Searching Center</p>
<p ><%= link_to 'Back', 'posts#index' %></p>
<p style="font-size: 2.4vw; font-weight: 900; color: yellow;">Searching for title that includes: <%= @result %></p>
</div>
	<% counter = 0 %>
	<% if @result == "" or @result == " " or @result == "  " or @result == "   " %>
		<p style="color: yellow; text-align: center; margin-top: 8%; margin-bottom: 7%; font-size: 3.7vw;">Your search cannot be blank!</p>
	<% else %>
	    <% @posts.each do |post| %>
	    	<% if post.title.include? @result %>
	    		<% counter = counter+1 %>
			    <div class="postlist">
			      <div style="font-size: 6vw; text-align: center;color:black; background-color: white; margin-bottom: -1.5%;">
			        <p><%= post.title %></p>
			      </div>
			      <div style="color:white; background-color: black; padding-top: 1%;">
			        <p><%= simple_format post.content %></p>
			        <p style="font-size: 1.8vw;">Author: <%= post.author %></p>
			        <p><%= post.created_at %>&nbsp;<%= post.updated_at %></p>
			        <p style="background-color: white; color:black;margin-bottom: 20%;"><%= link_to 'Showpost', post %></p>
			      </div>
			    </div>
			<% end %>
	    <% end %>
	    <% if counter == 0 %>
			<p style="color: yellow; text-align: center; margin-top: 8%; margin-bottom: 7%; font-size: 2.7vw;">Sorry, there is no blog that includes your keyword in the title :(</p>
		<% end %>
	<% end %>

Blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="intro" style="margin-top: 8%; margin-bottom: 5%; font-size: 1.7vw;">
<p>Posts</p>
</div>
<div class="postlist">
  <div style="font-size: 6vw; text-align: center;color:black; background-color: white; margin-bottom: -1.5%;">
    <p><%= @post.title %></p>
  </div>
  <div style="color:white; background-color: black; padding-top: 1%; ">
    <br>
      <div style="text-align: left; margin-left: 3%; margin-right: 3%; font-size: 24px; margin-bottom: 6%; margin-top: 6%;">
            <p><%= simple_format post.content %></p>
      </div>
    <br>
    <br>
    <p style="font-size: 1.8vw;">Author: <%= @post.author %></p>
    <p><%= @post.created_at %>&nbsp;<%= @post.updated_at %></p>
    <p style="background-color: white; color:black;margin-bottom: 20%;"><%= link_to 'Back', posts_path %></p>
  </div>
</div>

Blog/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Blog/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Blog/app/views/users/about.html.erb
<p id="notice"><%= notice %></p>
<div class="intro" style="margin-top: 8%; font-size: 2vw; margin-bottom: 2%;">
<p>About This Website</p>
<p style="font-size: 1.5vw;">关于我, 网站的一切</div>
<div class = "about" style="width: 50%; margin: 0 auto; height: auto; background-color: black; opacity: 0.8; color: white;"><br><br>
<p>INTRO</p>
<p>本来做这个博客和个人网站的目的是为了学习点新知识方便找实习。于是花了20刀大洋吧codeacademy的全栈工程师课程摸鱼摸鱼全弄完了（牺牲了守望先锋的时间），然后用学到的准备做个博客（后端）和个人主页（前端），一前一后岂不美哉：）。前端相对轻松，在12月份下半月lyulyulyu.com就基本全部搭好了，包括小鸟游戏，茶壶hemo和简历，当时有点令不清以为后端也会这么友好。因为codeacadmy最后学的是ruby，加上网上流传的“ruby on rails 15分钟搭建个人博客”视频，我就上了ruby on rails的贼船，从此一去不复返：）。</p>
<p>于是圣诞节前夕开始了这个博客搭建。自然首先打开了那个“15分钟”系列视频，结果光在linux上搭建ruby环境，install bundle就花了15分钟。。。总算可以开始敲代码了，发现这个视频教程是在ruby on rails 3运行的，而到我这里版本已经迭代到了5，3到4有一个大的更新，所以得另寻高人了。于是在半懂不懂的情况下自己凭映像摸索写controller，router和model，最后要吐血了，按照这个进度估计不是15分钟，要变成15个年了，肯定自己路线搞错了，遂到ruby官网查。。。结果发现了脚手架这个功能，之前在codeacademy由于程序比较简单，都是一些小的比如todolist，留言板blablabla所以没有教脚手架。。。从这以后仿佛看到了希望, 于是用脚手架命令1个小时就生成了一个超简陋版本的博客，和15分钟系列有几分神似，但是，凡事都有但是，我虽然知道怎么输入脚手架命令，背后的原理完全不懂。。。就像我会吃饭但是不会做饭一样，而且这个微博实在是太简陋，必须要添加新功能，而添加新功能需要理解原理，所以从头再来过。</p>
<p>好在车到山前必有路，我遇到了“ruby on rails教程”这本书，本来这玩意是没有中文版的，结果居然有雷锋把他翻译了！而且这书是随着ruby更新的，支持ruby on rials 5。打开一看，说的全是人话！于是仿佛久逢甘露，总算是开始步入正轨，开始搭建这个博客系统了。</p>
<p>LOG<p>
<p>v0.0 12/23 圣诞节前两天正式开始搭建博客（悲伤的故事）0功能<p>
<p>v0.5 12/26 ruby on rails看到第6章，利用脚手架完成基础，用户登录注册编辑删除功能完成，user的model，controller和router</p>
<p>v0.6 12/27 ruby on rails看到第8章，可以发博客了，blog的model，contoller和router</p>
<p>v0.7 12/28 ruby on rails看到第10章，用户权限系统, 博客编辑删除功能完成，增加session，id</p>
<p>v0.8 12/29 ruby on rails看到第11章，用户博客数据库各种关联，数据库seed设置，改各种逻辑bug，sql中的belong to关系</p>
<p>v0.9 12/31 规划了下整个网页关系，写了下router跳转逻辑，增加了如个人主页，发现博客等的功能页面，网站框架基本稳定了，改了好多bug<p>
<p>v1.0 1/2 本地版完成，没有美工丑哭，用的bookstrap的排版，ruby on rails看不下去了直接跳到最后一章12章，增加用户安全隔离，浏览器记忆，一堆if else</p>
<p>v1.5 1/4 本地美化版完成，写了很多很多css，jqury太懒没有写，网站美工ui设计完成，能看了，我爱上海</p>
<p>v2.0 1/5 网络版博客完成，被康哥安利了heroku，于是花了很久上传博客app到了heroku云端，设置了地址，把个人网页链接挂上了lyublog，于是博客正式在网络上线了</p>
<p>v2.1 1/6 发现一个大bug，本来发博客要求输入自己用户，要是输错了可能就变成别人的博客了，这个是书本上教了，非常的有问题。于是改了controller，取消了这个设定，花了蛮久的，最后换成了自动匹配用户</p>
<p>v2.5 1/7 出去滑雪去了。。期间一直在上网测试微博，发现一些问题</p> 
<p>v2.6 1/9 做不同浏览器窗口的大小匹配显示，因为博客里面文字很多，所以要是html css没写好，在不同大小分辨率的电脑上就会爆炸，于是把所有字体和div显示都改了</p>
<p>v3.0 1/10 全部完成！ 完善了用户逻辑，解决了小概率排版错误，迁移了heroku的db。暂时没有bug了！写了这个日志。纪念一下</p>
<p>v3.5 1/11 增加搜索引擎 在explore中，可以根据提供作者，或者标题，来查找匹配博客
<p>v4.0 1/12 修复博客没有“新行”的bug，增加gem simpletext包，渲染网页正文时会正确把回车转换成下一行。修复user列表最下用户在网页底端很难看见的bug。修复博客排版问题，取消居中。修复safari浏览器字体过细bug，强制取消像素自动抗锯齿。修复opera，safari等浏览器中文乱码问题，统一外部脚本试用UTF-8文字编码标准。</p>
<p>PS</p>
<p>最后，这个小博客算是长大成人了，感谢ruby的发明者，ruby on rails 确实是一个非常友好快速容易学习的后端方案，尤其感谢这本书的教导，使我在没有网络开发基础的情况下，快速上手。可惜之后找实习的打算全部取消了，商量后决定准备考研，这个博客可能没有它的出场机会了，真的很可惜， 学习写博客的过程非常的愉快。ruby 适合所有人, ruby gives coding fun.</p>
<br>
<br>
<br>
</div>

Blog/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="intro" style="margin-top: 8%; font-size: 2vw; margin-bottom: 2%;">
<p>Users</p>
<p style="font-size: 1.5vw;">海内存知己,天涯若比邻</p>
</div>
    <% @users.each do |user| %>
    <div class="postlist">
      <div style="font-size: 6vw; text-align: center;color:black; background-color: white; margin-bottom: -1.5%;">
        <p><%= user.name %></p>
      </div>
      <div style="color:white; background-color: black; padding-top: 1%; ">
        <p><%= user.email %></p>
        <p><%= link_to 'Show', user %>&nbsp;<% if current_user != nil && current_user.id == user.id%><%= link_to 'Edit', edit_user_path(user) %><% end %>&nbsp;<% if (current_user != nil && current_user.admin==true) || (current_user != nil && current_user.id == user.id)%>
          <%= link_to "delete", user, method: :delete,
          data: { confirm: "You sure?" } %>
        <% end %></p>
      </div>
    </div>
    <% end %>
    <br>
    <br>
    <br>
    <br>

Blog/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
	<div class="bloghead">
		<p>
		  <%= @user.name %>
		</p>
		<p style="font-size: 3vh; font-weight: 900; margin-top: -5%; margin-left: 30%;">
		  <%= @user.email %>
		</p>
		<p style="font-size: 2.5vh; font-weight: 100; margin-top: 5%;">
			但行好事，莫问前程
		</p>
	</div>
	<div class="bloghead2">
		<% if current_user != nil && current_user.id == @user.id%>
			<p><%= link_to 'New Post', new_post_path %></p>
		<% else %>
			<p><%= link_to 'New Post', root_path %></p>
		<% end %>
		<p>Posts (<%= @user.posts.count %>)</p>
	</div>
	<div class = "allpost">
		<% if @user.posts.any? %>
				<ol class="posts">
				<%= render @posts %>
				</ol>
				<%= will_paginate @posts %>
				<% else %>
	</div>
	<div style="font-size: 3.8vw; right: 10%; margin-top: 20%; position: absolute; color: white;">
				<p>You dont have any Post<p>
				<p>Any new IDEA for today?</p>
	<% end %>
	</div>

Blog/app/views/users/success.html.erb
<div style="margin: 0 auto; margin-top: 15%; text-align: center; color: white;">
<p style="font-size: 8vw; ">SUCCESS! </p>
<p style="font-size: 4vw; color: yellow;">厉害了我的用户</p>
<p style="font-size: 4vw; color: white;"><%= link_to 'HOME PAGE', root_path %></p>
</div>